simulation_configs:
  headless: false
  low_res: true

sim_actors:
  robot_arm:
    - name: "fancy_franka"
      position: [5.25, -25.0, 0.98]
    - name: "fancy_franka_2"
      position: [10.25, -25.0, 0.98]

  robot_quadruped:
    - name: "spot_blue"
      color: "blue"
      position: [0, 5] # Grid [column, row]
    - name: "spot_green"
      color: "green"
      position: [5, 0]  # Grid [column, row]
