simulation_configs:
  headless: false
  low_res: true

sim_actors:
  robot_arm:
    - name: "franka_1"
      position: [5.25, -27.5, 1.0]
    - name: "franka_2"
      position: [5.25, -25.0, 1.0]
    - name: "franka_3"
      position: [10.25, -26.0, 1.0]
  robot_quadruped:
    - name: "spot_1"
      color: "blue"
      position: [5.0, -5.0]
    - name: "spot_2"
      color: "blue"
      position: [7.0, -5.0]
    - name: "spot_3"
      color: "blue"
      position: [9.0, -5.0]
